yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path(
        'group/<slug>/', include('posts.urls', namespace='posts')
    ),
    path('about/', include('about.urls', namespace='about')),
    path('posts/', include('posts.urls', namespace='posts')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="following"
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'], name='unique_user_author'
            )
        ]

    def __str__(self):
        return self.user.username

yatube/posts/forms.py
from django import forms

from posts.models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from datetime import datetime
from typing import Dict

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render

from posts.forms import CommentForm, PostForm
from posts.models import Follow, Group, Post, User


def index(request: HttpRequest) -> HttpResponse:
    """Функция-обработчик для главной страницы. """
    posts: str = Post.objects.select_related('group').all()
    paginator = Paginator(posts, settings.NUMB)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context: Dict[str, str] = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request: HttpRequest, slug: str) -> HttpRequest:
    """Функция-обработчик для страницы с постами."""
    group: str = get_object_or_404(Group, slug=slug)
    posts: str = Post.objects.filter(group=group).all()
    paginator = Paginator(posts, settings.NUMB)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context: Dict[str, str] = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request: HttpRequest, username: str) -> HttpResponse:
    """Страница профайла пользователя, содержит инфо об авторе и посты."""
    author = get_object_or_404(User, username=username)
    posts = Post.objects.filter(author=author)
    posts_count = author.posts.count()
    paginator = Paginator(posts, settings.NUMB)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    user = request.user
    following = (
        user.is_authenticated and user.follower.filter(author=author).exists()
    )
    context = {
        'page_obj': page_obj,
        'author': author,
        'posts_count': posts_count,
        'user': user,
        'following': following,
    }

    return render(request, 'posts/profile.html', context)


def post_detail(request: HttpRequest, post_id: int) -> HttpResponse:
    """Подробная информация об отдельном посте."""
    post = get_object_or_404(Post, pk=post_id)
    group = post.group
    author = post.author
    posts_count = author.posts.count()
    comments = post.comments.all()
    form = CommentForm(request.POST or None)
    context = {
        'post': post,
        'group': group,
        'posts_count': posts_count,
        'comments': comments,
        'form': form,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request: HttpRequest) -> HttpResponse:
    """Создание нового поста."""
    if request.method != 'POST':
        form = PostForm(
            files=request.FILES or None
        )
        return render(request, 'posts/create_post.html', {'form': form})
    form = PostForm(
        request.POST,
        files=request.FILES or None
    )
    if not form.is_valid():
        return render(request, 'posts/create_post.html', {'form': form})
    post = form.save(commit=False)
    post.author = request.user
    post.pub_date = datetime.now()
    post.save()
    return redirect('posts:profile', request.user)


@login_required
def post_edit(request: HttpRequest, post_id) -> HttpResponse:
    """Редактирование поста."""
    template = 'posts/create_post.html'
    post = get_object_or_404(Post, id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if request.user != post.author:
        return redirect('posts:post_detail', post_id)
    if not form.is_valid():
        context = {
            'form': form,
            'is_edit': True
        }
        return render(request, template, context)
    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect('posts:post_detail', post_id)


@login_required
def add_comment(request: HttpRequest, post_id) -> HttpResponse:
    """Добавление комментария."""
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request: HttpRequest) -> HttpResponse:
    """
    Функция страницы постов авторов,
    на которых подписан текущий пользователь.
    """
    user = request.user
    authors = user.follower.values_list('author', flat=True)
    posts = Post.objects.filter(author__id__in=authors)
    paginator = Paginator(posts, settings.NUMB)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context: Dict[str, str] = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request: HttpRequest, username) -> HttpResponse:
    """Функция страницы подписки на авторов."""
    user = request.user
    author = get_object_or_404(User, username=username)
    if author != user:
        Follow.objects.get_or_create(user=user, author=author)
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request: HttpRequest, username) -> HttpResponse:
    """Функция страницы отписки от авторов."""
    user = request.user
    author = get_object_or_404(User, username=username)
    following = user.follower.filter(author=author)
    following.delete()
    return redirect('posts:profile', username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Новый пост {% endblock %}
{% block content %} 
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">       
            {% if is_edit %}
              Редактировать запись
            {% else %}
              Добавить запись
            {% endif %}            
          </div>
          <div class="card-body">        
            <form method="post" enctype="multipart/form-data">
              {% csrf_token %}            
              <div class="form-group row my-3 p-3">
                <label for="id_text">
                  Текст поста                  
                  <span class="required text-danger" >*</span>                  
                </label>
                <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text">
                </textarea>                
                <small id="id_text-help" class="form-text text-muted">
                  Текст нового поста
                </small>                  
              </div>            
              <div class="form-group row my-3 p-3">
                <label for="id_group">
                  Group                  
                </label>
                <select name="group" class="form-control" id="id_group">
                  {% for group in form.group %}
                    <option selected> {{group}} </option>
                  {% endfor %}
                </select>
                <small id="id_group-help" class="form-text text-muted">
                  Группа, к которой будет относиться пост
                </small>
              </div>
              <div class="form-group row my-3 p-3">
                <label for="id_image">
                  Картинка                      
                </label>
                <input type="file" name="image" accept="image/*" class="form-control" id="id_image">                      
              </div>
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
      {% include 'posts/includes/paginator.html' %}
    </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load cache %}
{% load thumbnail %}
{% load static %}
{% block title %}Мои подписки{% endblock %}
{% block content %}
  <div class="container py-5">     
    <h1>Мои подписки</h1>
    {% cache 20 index_page %}
        <article>
        {% include 'posts/includes/switcher.html' with follow=True %} 
          {% for post in page_obj %}
            <ul>
              <li>
                Автор: {{ post.author.get_full_name }}
              </li>
              <li>
                Дата публикации: {{ post.pub_date|date:"d E Y"}}
              </li>
            </ul>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
              <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            <p>{{ post.text }}</p>
            <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
            {% if post.group %}   
              <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            {% endif %}
        </article>
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% endcache %}
    {% include 'posts/includes/paginator.html' %}
  </div>  
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  {{ group.title }}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>{{ group.title }}</h1>
      <p>
        {{ group.description }}
      </p>
      {% for post in page_obj %}
        <article>
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
            </li>
            <li>
              Дата публикации:{{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}    
          <p>
            {{ post.text }}
          </p>         
        </article>
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>  
{% endblock %}
  

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load cache %}
{% load thumbnail %}
{% load static %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
  <div class="container py-5">     
    <h1>Последние обновления на сайте</h1>
    {% cache 20 index_page %}
        <article>
          {% include 'posts/includes/switcher.html' with index=True%}
          {% for post in page_obj %}
            <ul>
              <li>
                Автор: {{ post.author.get_full_name }}
              </li>
              <li>
                Дата публикации: {{ post.pub_date|date:"d E Y"}}
              </li>
            </ul>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
              <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            <p>{{ post.text }}</p>
            <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
            {% if post.group %}   
              <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            {% endif %}
        </article>
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% endcache %}
    {% include 'posts/includes/paginator.html' %}
  </div>  
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load user_filters %}
{% load thumbnail %}
{% block title %} Пост {{ post_id }} {% endblock %}
{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }} 
        </li>
        {% if post.group %}  
          <li class="list-group-item">
            Группа: {{ group.title }}
            <a href="{% url 'posts:group_list' post.group.slug %}">
              все записи группы
            </a>
          </li>
        {% endif %}
        <li class="list-group-item">
          Автор: {{ author.get_full_name }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span >{{ posts_count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author.username %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text }}</p>
      {% if user.is_authenticated %}
      <div class="card my-4">
        <h5 class="card-header">Добавить комментарий:</h5>
          <div class="card-body">
            <form method="post" action="{% url 'posts:add_comment' post.id %}">
              {% csrf_token %}      
              <div class="form-group mb-2">
                {{ form.text|addclass:"form-control" }}
              </div>
              <button type="submit" class="btn btn-primary">Отправить</button>
            </form>
         </div>
      </div>
      {% endif %}
      {% for comment in comments %}
        <div class="media mb-4">
          <div class="media-body">
            <h5 class="mt-0">
              <a href="{% url 'posts:profile' comment.author.username %}">
                {{ comment.author.username }}
              </a>
            </h5>
          <p>
            {{ comment.text }}
          </p>
          </div>
        </div>
      {% endfor %} 
    </article>
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %} Профайл пользователя {{ author.get_full_name }} {% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="mb-5">
      <h1>Все посты пользователя {{ author.get_full_name }}</h1>
      <h3>Всего постов: {{ posts_count }}</h3>
      {% if following %}
        <a
          class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' author.username %}" role="button"
        >
          Отписаться
        </a>
      {% else %}
          <a
            class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}" role="button"
          >
            Подписаться
          </a>
       {% endif %}
    </div>        
      <article>
        {% for post in page_obj %}
          <ul>
            <li>
              Автор: {{ author.get_full_name }}
              <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>
            {{ post.text }}
          </p>
          <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
        {% endfor %}
        </article>
        {% if post.group %}         
          <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        {% endif %}        
      <hr>
      {% if not forloop.last %}<hr>{% endif %}
    {% include 'posts/includes/paginator.html' %}  
  </div>
{% endblock %}